### PR TITLE
Define More Details Schema for Plugin Config

### LINKED ISSUE #46: Prepare a Schema Validation for the Configuration
Prepare schema for Provisioned Concurrency config to leverage SLS schema validation.

- [AWS uses Draft 04](https://docs.aws.amazon.com/apigateway/latest/developerguide/models-mappings.html#models-mappings-models)
- [Serverless can validate configuration against Schema with AVJ](https://www.serverless.com/framework/docs/configuration-validation)

This might be a contract breaking change. So i suggest to prepare it along with other changes for v2.0.0 of this plugin.

### PR DESCRIPTION
**Pull request by cookieMr**
Closes #46

### CODE REVIEW

**Comment by claydanford** [comment]
LGTM!

**Comment by nmrad-91** [comment]
@cookieMr is it safe to merge this code in?

**Comment by dboisse** [comment]
@nmrad-91 yes, this looks good to be merged, i see tests are in place

**Comment by cookieMr** [comment]
> @nmrad-91 yes, this looks good to be merged, i see tests are in place

@dboisse that me... this PR is good to merge, i wanted to do more tests and now this works for me

**Pull request merged**
